robot:
  type: uf::robot
  id: "uf_robot"
  robot_dof: 7
  control_space: "cartesian"
  robot_ip: "192.168.1.85"
  gripper_type: 10
  enable_logs: false
  max_linear_velocity: 200
  cameras:
    fisheye:
      type: opencv
      index_or_path: "/dev/v4l/by-id/usb-DECXIN_CAMERA_DECXIN_CAMERA_01.00.00-video-index0"
      width: 640
      height: 480
      fps: 30
      fourcc: "MJPG"

# make sure to edit with your correct configurations!
teleop:
  type: uf::pika_teleop
  # port: "/dev/ttyUSB0"
  scale_xyz: 1.5
  tracker_to_robot_eef: [0, 0, 0, 180, -90, 0]
  robot_base_pose: [400, 0, 400, 180, 0, 0]

dataset:
  # Dataset path relative to the directory where the command is started.
  root: "datasets/xarm7_pika_datas"
  repo_id: "ufactory/xarm7_pika_datas"
  single_task: "Pick up the purple grape and drop into the box on the left."
  fps: 30
  episode_time_s: 60  # max duration for one episode
  reset_time_s: 20    # (invalid) time for resetting env between episodes
  push_to_hub: False
