robot:
  type: uf::robot
  id: "uf_robot_cartesian"
  robot_dof: 7
  control_space: "cartesian"
  robot_ip: "192.168.1.245"
  gripper_type: 1
  max_linear_velocity: 200
  min_tcp_z_mm: 50
  gripper_error_log_path: "logs/xarm7_gripper_errors.log"
  cameras:
    camera:
      type: intelrealsense
      serial_number_or_name: "242622070583"
      width: 640
      height: 480
      fps: 30
    camera2:
      type: intelrealsense
      serial_number_or_name: "148522072685"
      width: 640
      height: 480
      fps: 30

teleop:
  type: uf::gello_teleop
  id: "gello_teleop"
  port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTB9HYVD-if00-port0"
  joint_ids: [1, 2, 3, 4, 5, 6, 7]
  joint_signs: [1, 1, 1, 1, 1, 1, 1]
  gripper_id: 8
  gripper_open_deg: 198.28125
  gripper_close_deg: 155.75

dataset:
  root: "datasets/xarm7_gello_cartesian_datas"
  repo_id: "ufactory/xarm7_gello_cartesian_datas"
  single_task: "Pick up the purple grape and drop into the box on the left."
  fps: 60
  episode_time_s: 60
  reset_time_s: 20
  push_to_hub: False
